Análise Titanic

In [151]:
import pandas as pd
import numpy as np

In [152]:
df = pd.read_csv('titanic.csv')

In [153]:
display(df)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [154]:
df_teste = df

In [155]:
df_teste = df_teste.drop(
    columns=[
        "Name",
        "Ticket",
        "Cabin",
        "Fare",
        "Parch"
    ]
)

Limpeza de Dados

In [156]:
df_teste

     PassengerId  Survived  Pclass     Sex   Age  SibSp Embarked
0              1         0       3    male  22.0      1        S
1              2         1       1  female  38.0      1        C
2              3         1       3  female  26.0      0        S
3              4         1       1  female  35.0      1        S
4              5         0       3    male  35.0      0        S
..           ...       ...     ...     ...   ...    ...      ...
886          887         0       2    male  27.0      0        S
887          888         1       1  female  19.0      0        S
888          889         0       3  female   NaN      1        S
889          890         1       1    male  26.0      0        C
890          891         0       3    male  32.0      0        Q

[891 rows x 7 columns]

In [157]:
df_teste.Sex.value_counts(dropna = False)

Sex
male      577
female    314
Name: count, dtype: int64

In [158]:
df_teste = pd.get_dummies(df_teste, dtype = int)

Transformação de dados categóricos em colunas

In [159]:
df_teste = df_teste.drop(
    columns = [
        "Sex_male",
        "Embarked_C",
        "Embarked_Q",
        "Embarked_S"
    ]
)

Retiramos a coluna Sex_male pois ela já é descoberta com a coluna Sex_female... Por enquanto não analisarei "Embarked"

In [160]:
df_teste = pd.get_dummies(df_teste, drop_first = True)

Imputação de dados:

In [161]:
from sklearn.impute import SimpleImputer

In [166]:
coluna = df_teste[["Age"]]

In [175]:
df_teste['Age'].median()

np.float64(28.0)

In [167]:
imputacao = SimpleImputer(strategy = "median")

In [164]:
df_teste["Age"] = imputacao.fit_transform(coluna)

Preenchimento de NaN pela mediana (28.0) de valores contidos na tabela.

In [177]:
df_teste

     PassengerId  Survived  Pclass   Age  SibSp  Sex_female
0              1         0       3  22.0      1           0
1              2         1       1  38.0      1           1
2              3         1       3  26.0      0           1
3              4         1       1  35.0      1           1
4              5         0       3  35.0      0           0
..           ...       ...     ...   ...    ...         ...
886          887         0       2  27.0      0           0
887          888         1       1  19.0      0           1
888          889         0       3  28.0      1           1
889          890         1       1  26.0      0           0
890          891         0       3  32.0      0           0

[891 rows x 6 columns]

Treinamento e Teste:

In [146]:
from sklearn.model_selection import train_test_split

In [147]:
y = df_teste.Survived
X = df.drop(columns="Survived")

In [148]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)